"""fix_centro_treinamento_id

Revision ID: e41c50398415
Revises: 2f08a6d30c3f
Create Date: 2025-08-26 02:36:28.158151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e41c50398415'
down_revision: Union[str, Sequence[str], None] = '2f08a6d30c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('centro_treinamento_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('atletas_centro_treinamneto_id_fkey'), 'atletas', type_='foreignkey')
    op.create_foreign_key(None, 'atletas', 'centros_treinamento', ['centro_treinamento_id'], ['pk_id'])
    op.drop_column('atletas', 'centro_treinamneto_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('centro_treinamneto_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'atletas', type_='foreignkey')
    op.create_foreign_key(op.f('atletas_centro_treinamneto_id_fkey'), 'atletas', 'centros_treinamento', ['centro_treinamneto_id'], ['pk_id'])
    op.drop_column('atletas', 'centro_treinamento_id')
    # ### end Alembic commands ###
